apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

namespace: staging

commonLabels:
  app.kubernetes.io/version: v0.0.12
  app.kubernetes.io/environment: staging

configMapGenerator:
- name: k8s-simple-app
  files:
  - config.json=config/config.json
  options:
    disableNameSuffixHash: true

images:
- name: lbogdan/k8s-simple-app-2
  newTag: v0.0.12

patchesStrategicMerge:
- sealedsecret.yaml

patches:
- path: ingress_patch.json
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: k8s-simple-app
