apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k8s-simple-app
  namespace: staging
spec:
  encryptedData:
    SECRET_DATABASE_PASSWORD: AgBOqFmb/XBH8fWTMVVtHj5jVKOk+eqWzqmGzOWd1VCYKtH4+Gw7qcH28QDwaA8F+rDAGevY5RyzSJ4kZAX3P4KKfLtPG6RQZY9MtZD2/ufXQmbnbNvfwgCKko3NwQ4y75aSGn5s3MHABSzb5BKvUUuLJ5k7qHxixKctREmp5o52n+jHtsFUmL6WO/kIHivoB7ywNAPukWdopMSgck+DBwx5NfWTskL0w8//bUMhoMNe85Ih9bxbgtwd9nP5BAjgJQ+JBHseD6sqBKNI6SSFKWakRKoWHaBBxLK8vnfSgMr+hcT0dqWLszPXYSXm/4pH0S3mOkITYlhOr62UziZCPonPKFWJkzrNLv1FqTaIieF6qxiGlAXP7oUs9E8U8YRtlx++u5n2MxGeO4n9b8UMRN+rLsxS0obVyAvjZvBGGDYiEkjK535OhTcGzHgBh9QpgSphbhVaDEmPkzOdDoe9+ZTZYV9ZtC3oDSfqFyurNvN1vjTacqsd/E3XIslcUT45KT0fT6gCQb14USnKxUwgFXunuddg6dAzC7yFvEV8aAAcxoGvr8V/UObmf6LyVDpZbppBdger1pJWKPcQMq8du74pViRkuDuropek4B1pJuv+5snyLyvZ2CE2gxPYOauZYV2VmlnM6IYn0BV5f95mUrJ+Q8lPQKC3QuEi96p6yKQzdZwyC8FCjtNBzLYUgRYrUp6SfDGK/0+rgzD0i/MrgUlxAcXPo0mGKOs4
  template:
    metadata:
      labels:
        app.kubernetes.io/environment: staging
        app.kubernetes.io/name: k8s-simple-app
        app.kubernetes.io/version: v0.0.1
      name: k8s-simple-app
      namespace: staging
