apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k8s-simple-app
  namespace: staging
spec:
  encryptedData:
    SECRET_DATABASE_PASSWORD: AgBf6YVKIDdr4J1SRsP+u6Wiqahj2BiYSWRDfbTzz5DlaQ7MPFOTLJxtvTMmpD7N+KXMD9zQoU8HJoHkkCgrVxkkQMIjXblfrBsSJVObgRefXNCu5SJLQKr9eAVZpZ/tadrX9LJ75TZObPvhsLrKlwRhYvGJIxOMjk/bw6qePENkoaEX9bkVUC+QGf79dWZsM59RoJpGE9anrFZJEnQYfZtiOb8qTzZ3S1Exaen44uNWLBapckziGp8bbnTsr01tCq9+nJsKOyy2UCVblPTyiBOtuZLNX5XhEbULkcyD8SJib4Tiec+EwlgNxTmkUyzWpzsmClpDISaTxtO9Jjf9Y2limiANPmOkoWH3X0MWyYMRAGmoXGNaBMletLkM2qvUyvxfC6d1T9QpoFadr7FhZFjWwmMRTAEuG/5hHiomMA/E6/PbK/pTVaUlXheGLUjAvMIxHVXW2K0T23Ik3UVy3bZ4Ri3yU3acq6aEUrwAm0lQG1odIxP1V7Ntbpr8fJWA6yORqFdCyMNZDNqfUlqfKO7t6bZNqbxrtKUHJoWChdDhalyeuLDI1/cTl5baFBys1qbaOb9ZPfscfraszqzDFC+CiuWkhD9Zsky1cQ+R8k7+XbXgPdV9XK5pRsjPn+QqpitOB4bXqCkZTN2QFBP5x8QZPF+fLByrhxrbNwnRB+GKyWhgMCFwaeDSU+yQTVJXR6sokgiSv4xyo9NPhEI=
  template:
    metadata:
      labels:
        app.kubernetes.io/environment: staging
        app.kubernetes.io/name: k8s-simple-app
        app.kubernetes.io/version: v0.0.1
      name: k8s-simple-app
      namespace: staging
