apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sealedsecret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: k8s-simple-app

configurations:
- config/sealedsecret.yaml
